### ISSUE TITLE
极路由1s    openwrt18.06.1在接口界面出现错误

### ISSUE THREAD

**Issue by ghost** [chenhaowen01/gdut-drcom-for-openwrt#12]
极路由1s    openwrt18.06.1   gdut-drcom1.6.8，只能在gdut-drcom client 里使用enable pppoe dial拨号，在接口处按wan接口的重启会提示‘错误（user-request）’

**Comment by xnhw01** [comment]
只在18.06.1上出现吗

**Comment by LeoLinbbbb** [comment]
貌似是的

**Comment by xnhw01** [comment]
好的，可能是新版本的OpenWrt改了一些东西。有时间我会看一下，现在手头上也没有刷了18.06的路由。
