### ISSUE TITLE
你好，编译过程遇到一些问题

### ISSUE THREAD

**Issue by maodreamer** [chenhaowen01/gdut-drcom-for-openwrt#3]
开始第一次编译让添加-j1 V=s
添加后出现报错
请问是什么原因，是环境的原因吗

hhh@hhh-OMEN-by-HP-Laptop:~/OpenWrt-SDK-15.05.1-ramips-mt7628_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ make package/gdut-drcom/compile
awk: include/scan.awk: line 21: function asort never defined
awk: include/scan.awk: line 21: function asort never defined
awk: include/scan.awk: line 21: function asort never defined
awk: include/scan.awk: line 21: function asort never defined

  configuration written to .config

 make[1] package/gdut-drcom/compile
**make -r package/gdut-drcom/compile: build failed. Please re-run make with -j1 V=s to see what's going on
/hom**e/hhh/OpenWrt-SDK-15.05.1-ramips-mt7628_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/toplevel.mk:174: recipe for target 'package/gdut-drcom/compile' failed
make: *** [package/gdut-drcom/compile] Error 1

hhh@hhh-OMEN-by-HP-Laptop:~/OpenWrt-SDK-15.05.1-ramips-mt7628_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64$ make package/gdut-drcom/compile -j1 V=s
awk: include/scan.awk: line 21: function asort never defined
awk: include/scan.awk: line 21: function asort never defined
awk: include/scan.awk: line 21: function asort never defined
awk: include/scan.awk: line 21: function asort never defined

 configuration written to .config

make[1]: Entering directory '/home/hhh/OpenWrt-SDK-15.05.1-ramips-mt7628_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
make[1]: *** No rule to make target 'package/gdut-drcom/compile'.  Stop.
make[1]: Leaving directory '/home/hhh/OpenWrt-SDK-15.05.1-ramips-mt7628_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64'
/home/hhh/OpenWrt-SDK-15.05.1-ramips-mt7628_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/include/toplevel.mk:174: recipe for target 'package/gdut-drcom/compile' failed
make: *** [package/gdut-drcom/compile] Error 2

**Comment by chenhaowen01** [comment]
没有复现的你问题，请检查是否缺少gawk依赖。
