### ISSUE TITLE
最近经常性无法上网 T _ T

### ISSUE THREAD

**Issue by z5n0w** [chenhaowen01/gdut-drcom-for-openwrt#4]
重连一次大概能用5-15分钟
过一段时间后就不能上网了
留意过断网前连接数疯狂飙升，连接数从六七百一直蹿升到一千二三
检查发现这一千多个连接中超过1/3都是DNS请求
emmm…………
![image](https://user-images.githubusercontent.com/10935328/33326210-4d86bc7c-d48f-11e7-872c-d87e72dfa3bc.png)

这时候网页的报错基本都是：
DNS_PROBE_FINISHED_NO_INTERNET

**Comment by chenhaowen01** [comment]
什么情况的断网，PPPoE断开会自动重拨，心跳服务掉线也会自动重连，请详细说明。
另外，gdut-drcom不处理DNS请求，请检查其他服务或者内网设备。

**Comment by z5n0w** [comment]
网没断，但完全没有速度。表现为DNS大量超时=_=||

**Comment by z5n0w** [comment]
现在又重新变得稳定多了
