### ISSUE TITLE
ipk包无法安装

### ISSUE THREAD

**Issue by YorkPeng** [chenhaowen01/gdut-drcom-for-openwrt#6]
你好，ipk包在OpenWrt Chaos Calmer 15.05.1上无法安装，设备是K2P（MT7621），请问该如何解决这个问题呢？

报错：/$ opkg install gdut-drcom_1.6.8-3_ramips_24kec_uClibc.ipk
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for gdut-drcom found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package gdut-drcom.
Unknown package 'gdut-drcom'.

**Comment by chenhaowen01** [comment]
1. 你可以试一下用cc 15.05.1的SDK自己编译试一下
2. 不要通过opkg安装，把ipk把解开手动安装试一下，ipk包实际上是一个*.tar.gz但tarball

**Comment by YorkPeng** [comment]
Thanks
