### ISSUE TITLE
编译第一步tar x........遇到的问题

### ISSUE THREAD

**Issue by LeoLinbbbb** [chenhaowen01/gdut-drcom-for-openwrt#8]
tar: invalid option -- j
BusyBox v1.22.1 (2016-05-16 21:57:43 CST) multi-call binary.

Usage: tar -[cxtzhvO] [-X FILE] [-T FILE] [-f TARFILE] [-C DIR] [FILE]...

Create, extract, or list files from a tar file

Operation:
        c       Create
        x       Extract
        t       List
        f       Name of TARFILE ('-' for stdin/out)
        C       Change to DIR before operation
        v       Verbose
        z       (De)compress using gzip
        O       Extract to stdout
        h       Follow symlinks
        X       File with names to exclude
        T       File with names to include

**Comment by xnhw01** [comment]
不要使用busybox的tar实现
